swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.simple.com
basePath: /v1
schemes:
  - http

paths:
  /hello:
    get:
      tags:
        - hello
      operationId: GetHello
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/hello_reply'

definitions:
  hello_reply:
    properties:
      reply:
        type: string