// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API description in Markdown.",
    "title": "Sample API",
    "version": "1.0.0"
  },
  "host": "api.simple.com",
  "basePath": "/v1",
  "paths": {
    "/hello": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "hello"
        ],
        "operationId": "GetHello",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/hello_reply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "hello_reply": {
      "properties": {
        "reply": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API description in Markdown.",
    "title": "Sample API",
    "version": "1.0.0"
  },
  "host": "api.simple.com",
  "basePath": "/v1",
  "paths": {
    "/hello": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "hello"
        ],
        "operationId": "GetHello",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/hello_reply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "hello_reply": {
      "properties": {
        "reply": {
          "type": "string"
        }
      }
    }
  }
}`))
}
